// Questionnaire data: 50 questions by section
// Used only on this machine; data stored in localStorage.
// Exposed globally for app.js (open index.html in browser, no server).
// Bump QUESTIONNAIRE_VERSION when adding sections/questions or changing structure; see FUTURE-PROOFING.md.

var QUESTIONNAIRE_VERSION = 1;

var SECTIONS = [
  { id: 'money', label: 'Money' },
  { id: 'structure', label: 'Relationship Structure' },
  { id: 'children', label: 'Children' },
  { id: 'sex', label: 'Sex' },
  { id: 'downtime', label: 'Downtime & Hobbies' },
  { id: 'communication', label: 'Communication & Conflict' },
  { id: 'scheduling', label: 'Time & Scheduling' },
  { id: 'metamours', label: 'New Partners & Metamours' },
  { id: 'partner_dating', label: 'Partner dating & disclosures' },
  { id: 'disclosure', label: 'Disclosure & Privacy' },
  { id: 'hierarchy', label: 'Hierarchy & Prioritization' },
  { id: 'emotional', label: 'Emotional Needs & Support' },
  { id: 'boundaries', label: 'Boundaries & Agreements' },
  { id: 'health', label: 'Health & Risk' },
  { id: 'legal', label: 'Long-Term & Legal' },
  { id: 'values', label: 'Values & Lifestyle' },
];

var QUESTIONS = [
  { id: 1, section: 'money', text: 'Do you wish to be independent with your money?', type: 'choice', options: ['Yes', 'No', 'Partially / It depends'] },
  { id: 2, section: 'money', text: 'Do you wish to have shared finances?', type: 'choice', options: ['Yes', 'No', 'Partially (e.g., shared account for household only)'] },
  { id: 3, section: 'money', text: 'Do you wish to buy property with a partner?', type: 'choice', options: ['Yes', 'No', 'Maybe / It depends'] },
  { id: 4, section: 'money', text: 'Do you think financial decisions should be made between all of your partners?', type: 'choice', options: ['Yes, all partners', 'Only partners who share finances', 'No, each dyad decides', 'Other'] },
  { id: 5, section: 'structure', text: 'Do you wish to cohabitate with your partner full time, part time, or not at all?', type: 'choice', options: ['Full time', 'Part time', 'Not at all', 'It depends on the partner'] },
  { id: 6, section: 'structure', text: 'Do you wish to become married legally?', type: 'choice', options: ['Yes', 'No', 'With one partner only', 'Open to multiple if legally possible', 'Unsure'] },
  { id: 7, section: 'structure', text: 'Do you wish to become married civilly?', type: 'choice', options: ['Yes (commitment ceremony / non-legal marriage)', 'No', 'It depends'] },
  { id: 8, section: 'children', text: 'Do you wish to have more children?', type: 'choice', options: ['Yes', 'No', 'Unsure', 'Not applicable'] },
  { id: 9, section: 'children', text: 'Do you wish to raise children with your partner(s)?', type: 'choice', options: ['Yes', 'No', 'With some partners only', 'Unsure'] },
  { id: 10, section: 'children', text: 'Do you wish to coparent your partner\'s kids?', type: 'choice', options: ['Yes', 'No', 'In a limited role (e.g., occasional care)', 'It depends on the situation'] },
  { id: 11, section: 'sex', text: 'At what frequency do you need sex?', type: 'choice', options: ['Daily', 'Several times a week', 'Weekly', 'A few times a month', 'Monthly or less', 'Quality matters more than frequency', 'Other'] },
  { id: 12, section: 'sex', text: 'Do you require condoms with new partners?', type: 'choice', options: ['Yes, always', 'Until STI testing / conversation', 'No', 'Other'] },
  { id: 13, section: 'sex', text: 'Do you think your partner should disclose sexual relations had outside of the polycule?', type: 'choice', options: ['Yes, before it happens', 'Yes, after', 'Yes, only if it affects risk (e.g., barrier use)', 'No', 'Other'] },
  { id: 14, section: 'sex', text: 'Do you think your partner should disclose sexual relations had inside of the polycule?', type: 'choice', options: ['Yes, before', 'Yes, after', 'No', 'Only if I ask', 'Other'] },
  { id: 15, section: 'downtime', text: 'How often do you need alone time?', type: 'choice', options: ['Daily', 'Several times a week', 'Weekly', 'A few times a month', 'Rarely', 'Other'] },
  { id: 16, section: 'downtime', text: 'How often do you need time with your hobbies?', type: 'choice', options: ['Daily', 'Several times a week', 'Weekly', 'A few times a month', 'Rarely', 'Other'] },
  { id: 17, section: 'downtime', text: 'Do you wish to share in your hobbies with your partner(s)?', type: 'choice', options: ['Yes, as much as possible', 'Some hobbies only', 'No, I prefer hobbies as solo/separate', 'It depends'] },
  { id: 18, section: 'downtime', text: 'Where is downtime best had?', type: 'choice', options: ['My home', 'Partner\'s home', 'Outdoors', 'In public', 'Mix / no preference', 'Other'] },
  { id: 19, section: 'communication', text: 'How do you prefer to handle serious relationship conversations?', type: 'choice', options: ['In person only', 'Can include text/voice after initial in-person', 'Willing to do video calls', 'No strong preference'] },
  { id: 20, section: 'communication', text: 'When conflict arises, how quickly do you need to address it?', type: 'choice', options: ['Immediately', 'Within 24–48 hours', 'When we can schedule a calm conversation', 'After I\'ve had time to process alone', 'Other'] },
  { id: 21, section: 'communication', text: 'Do you want to be included in conversations about agreements that affect you?', type: 'choice', options: ['Yes, always', 'Yes, for major agreements', "I'm okay being informed after", 'It depends'] },
  { id: 22, section: 'communication', text: 'How much detail do you want about your partner\'s other relationships?', type: 'choice', options: ['High level only (e.g., "we\'re good")', 'Emotional updates when relevant', 'As much as they\'re willing to share', 'I prefer not to know details', 'Other'] },
  { id: 23, section: 'scheduling', text: 'How do you want scheduling and calendar sharing to work?', type: 'choice', options: ['Shared calendar visible to all', 'Partners share dates that affect me', 'No shared calendar; we communicate as needed', 'Other'] },
  { id: 24, section: 'scheduling', text: 'How much advance notice do you need for plans that affect our time together?', type: 'choice', options: ['As much as possible', 'At least a few days', 'At least 24 hours', 'Same day is fine', 'No set expectation'] },
  { id: 25, section: 'scheduling', text: 'Do you need dedicated one-on-one time with each partner on a regular basis?', type: 'choice', options: ['Yes, and I have a minimum frequency in mind', 'Yes, but flexible on frequency', 'No', 'Other'] },
  { id: 26, section: 'scheduling', text: 'How do you feel about last-minute changes to planned time?', type: 'choice', options: ['Generally okay if communicated', 'Frustrating; I prefer commitment to plans', 'Depends on reason and how often', 'Other'] },
  { id: 27, section: 'metamours', text: 'When a partner is considering a new relationship, what do you want?', type: 'choice', options: ['To know before they pursue it', 'To know once it\'s becoming serious', 'To know when it affects our time/agreements', 'No need to know in advance', 'Other'] },
  { id: 28, section: 'metamours', text: 'Do you want to meet your metamours (partner\'s other partners)?', type: 'choice', options: ['Yes, ideally', 'Yes, if it\'s going to be ongoing', 'Optional / no strong preference', 'Prefer not to', 'Other'] },
  { id: 29, section: 'metamours', text: 'Are you open to group activities (e.g., all of us together) as a polycule?', type: 'choice', options: ['Yes, regularly', 'Yes, occasionally', 'Rarely', 'No', 'Other'] },
  { id: 30, section: 'metamours', text: 'Do you need veto power or "messy list" discussions (people/situations that are off limits)?', type: 'choice', options: ['Yes, I want veto or a messy list', 'I want to discuss, but not necessarily veto', 'No', 'Unsure'] },
  { id: 51, section: 'metamours', text: 'Do you want to know your metamours?', type: 'choice', options: ['Yes, I want to know who they are', 'Yes, ideally meet them', 'Prefer not to know', 'No strong preference', 'Other'] },
  { id: 52, section: 'metamours', text: 'Do you want to have a connection to your metamours?', type: 'choice', options: ['Yes, I\'d like a real friendship', 'Yes, friendly is enough', 'Civil is enough', 'No connection needed', 'Other'] },
  { id: 53, section: 'metamours', text: 'Could you live with a metamour?', type: 'choice', options: ['Yes', 'No', 'In certain circumstances (e.g., separate spaces)', 'Unsure', 'Other'] },
  { id: 54, section: 'partner_dating', text: 'How do you feel when your partner is dating or interested in someone else?', type: 'choice', options: ['Generally comfortable', 'I need reassurance', 'I prefer not to dwell on it', 'It varies; I want to talk when it\'s hard', 'Other'] },
  { id: 55, section: 'partner_dating', text: 'Do you want to be informed when your partner has a date?', type: 'choice', options: ['Before (so I know it\'s happening)', 'After', 'Only if it affects our plans', 'Prefer not to know', 'Other'] },
  { id: 56, section: 'partner_dating', text: 'What do you want to know when your partner starts seeing someone new?', type: 'choice', options: ['Just that it\'s happening', 'How they\'re feeling about it', 'Details as they\'re comfortable sharing', 'As little as possible', 'Other'] },
  { id: 57, section: 'partner_dating', text: 'When do you want your partner to tell you about a new person (before first date, after, or when ongoing)?', type: 'choice', options: ['Before a first date', 'After the first date', 'When it becomes ongoing', 'When it affects our time or agreements', 'Other'] },
  { id: 58, section: 'partner_dating', text: 'Do you expect to date others as well, or is that not a priority for you?', type: 'choice', options: ['Yes, I want to date others too', 'Maybe someday', 'No, I\'m not interested in more partners right now', 'It depends', 'Other'] },
  { id: 59, section: 'partner_dating', text: 'How do you feel about your partner dating when you are not currently dating others?', type: 'choice', options: ['Fine', 'I prefer we\'re in a similar place when possible', 'I need extra reassurance when I\'m not dating', 'Other'] },
  { id: 60, section: 'partner_dating', text: 'Do you have expectations about how often or how much your partner dates?', type: 'choice', options: ['No set expectation', 'We\'ll check in if it affects our time', 'I\'d like to discuss if it changes significantly', 'Other'] },
  { id: 31, section: 'disclosure', text: 'Who do you want to know about your polyamorous structure?', type: 'choice', options: ['Close family', 'Friends', 'Work / professional', 'No one', 'Select people only', 'Other'] },
  { id: 32, section: 'disclosure', text: 'Do you expect partners to be "out" to the same people you are?', type: 'choice', options: ['Yes', 'No', 'Only in shared contexts', 'We can decide per partner', 'Other'] },
  { id: 33, section: 'disclosure', text: 'How do you feel about PDA (public displays of affection) with a partner when other partners or metamours might see?', type: 'choice', options: ['Comfortable', 'Prefer to keep it moderate in group', 'Uncomfortable', 'Depends on context', 'Other'] },
  { id: 34, section: 'hierarchy', text: 'Do you want a clearly defined primary (or anchor) partner?', type: 'choice', options: ['Yes, I want that structure', 'No', 'I\'m open to it but not required', 'Other'] },
  { id: 35, section: 'hierarchy', text: 'When partners\' needs conflict (e.g., two want the same evening), how should it be decided?', type: 'choice', options: ['Pre-agreed hierarchy', 'Rotating or fair scheduling', 'Case-by-case conversation', 'No single rule', 'Other'] },
  { id: 36, section: 'hierarchy', text: 'Do you want holidays or special occasions to be shared, split, or flexible?', type: 'choice', options: ['Shared as a polycule when possible', 'Split between partners', 'Flexible / alternate years', 'No strong preference', 'Other'] },
  { id: 37, section: 'emotional', text: 'How do you want to be supported when you\'re struggling (e.g., jealousy, insecurity)?', type: 'choice', options: ['Reassurance and more connection', 'Space and time to process', 'Practical agreements (e.g., check-ins)', 'Mix; I\'ll say what I need', 'Other'] },
  { id: 38, section: 'emotional', text: 'Do you want relationship check-ins (scheduled conversations about how things are going)?', type: 'choice', options: ['Yes, regularly (e.g., monthly)', 'Yes, occasionally', 'Only when something feels off', 'No', 'Other'] },
  { id: 39, section: 'emotional', text: 'How important is it that your partners get along with each other?', type: 'choice', options: ['Very; I want kitchen table poly', 'Somewhat; at least civil', 'Not necessary; parallel is fine', 'Other'] },
  { id: 40, section: 'emotional', text: 'Do you need explicit reassurance when a partner has a new connection or is NRE (new relationship energy)?', type: 'choice', options: ['Yes', 'Sometimes', 'No', 'Other'] },
  { id: 41, section: 'boundaries', text: 'Do you want written or clearly stated agreements that everyone can refer back to?', type: 'choice', options: ['Yes, written', 'Yes, but verbal is fine', 'Prefer to keep things flexible', 'Other'] },
  { id: 42, section: 'boundaries', text: 'When an agreement is broken, what do you expect?', type: 'choice', options: ['Immediate conversation and repair', 'Conversation and possibly renegotiation', 'Depends on severity', 'Other'] },
  { id: 43, section: 'boundaries', text: 'Are you okay with agreements changing over time as people or situations change?', type: 'choice', options: ['Yes, with conversation', 'Yes, but I want to be part of the conversation', 'I prefer stability', 'Other'] },
  { id: 44, section: 'health', text: 'How do you want STI testing and risk to be handled?', type: 'choice', options: ['Regular testing and sharing results within polycule', 'Testing when new partner added; share with affected partners', 'Personal choice; disclose only if risk changes', 'Other'] },
  { id: 45, section: 'health', text: 'Do you want to know about barrier use (condoms, etc.) between your partner and others?', type: 'choice', options: ['Yes', 'Only if it changes (e.g., they stop using barriers)', 'No', 'Other'] },
  { id: 46, section: 'legal', text: 'Do you want to be included in long-term planning (e.g., retirement, caregiving) with your partner(s)?', type: 'choice', options: ['Yes', 'With primary/anchor only', 'Discuss when relevant', 'No', 'Other'] },
  { id: 47, section: 'legal', text: 'Are you open to legal arrangements (e.g., POA, healthcare proxy) with a partner?', type: 'choice', options: ['Yes', 'With one partner', 'With more than one if possible', 'No', 'Unsure', 'Other'] },
  { id: 48, section: 'legal', text: 'How do you feel about end-of-life or emergency contact designation?', type: 'choice', options: ['I want a partner included', 'I\'m open to it', 'Prefer to keep legal/family separate', 'Other'] },
  { id: 49, section: 'values', text: 'How aligned do you need to be with partners on big life values (e.g., religion, politics, lifestyle)?', type: 'choice', options: ['Very aligned', 'Respectful difference is okay', 'Don\'t need alignment', 'Other'] },
  { id: 50, section: 'values', text: 'What does "commitment" mean to you in a polyamorous context?', type: 'text', placeholder: 'A few sentences' },
];
